[tool.openhubble]
name = "OpenHubble Agent"
version = "2.10.4"
description = "Lightweight system monitoring agent"
authors = ["OpenHubble Team <team@openhubble.com>"]

[tool.openhubble.dependencies]
python = ">=3.8"
